using ThreeCommerce.BuildingBlocks.Contracts.Payments;

namespace ThreeCommerce.Workers.Notifications.Email;

/// <summary>
/// Versioned-in-repo templates. The storefront base URL is configured so links
/// point at the public site, not internal services.
/// </summary>
public sealed class EmailTemplates(string storefrontBaseUrl)
{
    public EmailMessage Verification(string to, string token) => new(
        to,
        "Verify your email address",
        $"Welcome to 3commerce. Confirm your address: {storefrontBaseUrl}/verify-email?token={token}");

    public EmailMessage PasswordReset(string to, string token) => new(
        to,
        "Reset your password",
        $"Reset your password here (expires in 1 hour): {storefrontBaseUrl}/reset-password?token={token}");

    public EmailMessage OrderConfirmed(string to, Guid orderId, long amountMinor, string currency) => new(
        to,
        "Your order is confirmed",
        $"Thanks for your purchase. Order {orderId} for {amountMinor / 100m:0.00} {currency} is confirmed. "
            + $"Track it at {storefrontBaseUrl}/orders/{orderId}.");

    public EmailMessage TrackingAssigned(string to, Guid orderId, string carrier, string trackingNumber) => new(
        to,
        "Your order has shipped",
        $"Order {orderId} is on its way via {carrier}. Tracking number: {trackingNumber}.");

    public EmailMessage TicketOpened(string to, Guid ticketId, Guid orderId) => new(
        to,
        "We received your support request",
        $"Your ticket {ticketId} for order {orderId} is open. We'll be in touch shortly.");

    public EmailMessage RmaStateChanged(string to, Guid rmaId, string state) => new(
        to,
        $"Your return/refund request is now {state}",
        $"Update on your request {rmaId}: status is now {state}.");

    /// <summary>
    /// TEST-ONLY mock-payment payload email (pay_3, ADR-0039). Clearly labelled, and NEVER sent in
    /// Production (the event is never published there). The redacted payload from
    /// <c>MockPaymentCaptured.RedactedPayloadJson</c> is embedded verbatim — it already excludes
    /// PAN/CVV/wallet tokens and masks provider payment-method refs to last-4.
    /// </summary>
    public EmailMessage MockPayment(string to, MockPaymentCaptured e)
    {
        var amount = e.AmountMinor / 100m;
        var subject = $"[TEST ONLY / MOCK PAYMENT] {e.Operation} order {e.OrderId} — {amount:0.00} {e.Currency} via {e.Provider}/{e.MethodKind}";
        var body =
            "================= TEST ONLY / MOCK PAYMENT =================\n" +
            "This email was generated by 3commerce running in a test mode\n" +
            "(LocalMock/Sandbox). NO money moved. It shows the payment request\n" +
            "that WOULD have been sent to the provider. Never sent in Production.\n" +
            "===========================================================\n\n" +
            $"Operation:  {e.Operation}\n" +
            $"Order:      {e.OrderId}\n" +
            $"Tenant:     {e.TenantId}\n" +
            $"Provider:   {e.Provider}    Mode: {e.Mode}\n" +
            $"Method:     {e.MethodKind}\n" +
            $"Scenario:   {e.Scenario}\n" +
            $"Amount:     {amount:0.00} {e.Currency}    Intent: {e.PaymentIntentId}\n" +
            $"Captured:   {e.CapturedAt:u}\n\n" +
            "--- Provider request payload (redacted) ---\n" +
            e.RedactedPayloadJson + "\n" +
            "-------------------------------------------\n" +
            "walletToken / PAN / CVV are never included.";
        return new EmailMessage(to, subject, body);
    }
}
